% Code-Auto Generated By jmp8430 using gmt Toolbox on 11-Mar-2026 14:09:13
% Inputs 
u6 = 0; % MainTank: Inlet Mass Flow 1 (Units: kg/s)
u7 = 1.5; % MainTank: Outlet Mass Flow 1 (Units: kg/s)
u8 = 0; % RecirTank: Inlet Mass Flow 1 (Units: kg/s)
u9 = 0; % RecirTank: Outlet Mass Flow 1 (Units: kg/s)
% Boundary Conditions
x2 = 0; % CoolerLoad: Energy Applied (Units: W)
x6 = 0; % HeatLoad: Energy Applied (Units: W)
x10 = 0; % MainTank: Source Temperature (Units: K)
% Simulation Time
SimTEnd = 2000;
% Initial Conditions
x1_0 = 1;  % CoolerLoad: Load Temperature (Units: K)
x3_0 = 1;  % EngineSplit: Junction Fluid Temperature (Units: K)
x5_0 = 1;  % HeatLoad: Load Temperature (Units: K)
x7_0 = 1;  % MainTank: Temperature (Units: K)
x8_0 = 6000;  % MainTank: Mass (Units: kg)
x12_0 = 1;  % RecirTank: Temperature (Units: K)
x13_0 = 1;  % RecirTank: Mass (Units: kg)
x16_0 = 1;  % TankSplit: Junction Fluid Temperature (Units: K)
y0 = [x1_0,x3_0,x5_0,x7_0,x8_0,x12_0,x13_0,x16_0];
[t, y] = ode23s(@(t,y) sysFun_FuelSystem(t,y,u6,u7,u8,u9,x2,x6,x10), [0 SimTEnd], y0);
% Plot Only Internal State Types
InternalIdx = ([FuelSystem.Vertices.VertexType] == gmt_VertexType.Internal);
NumInternal = size(y,2);
DimSubPlot = max(ceil(sqrt(NumInternal)),2);
ylabels_tmp = [FuelSystem.Vertices(InternalIdx).VertexName];
ylabelsnew_tmp = replace(ylabels_tmp, ":", newline);
figure
for i = 1:NumInternal
    subplot(DimSubPlot,DimSubPlot,i)
    plot(t,y(:,i))
    xlabel('Time')
    ylabel(ylabelsnew_tmp(i))
end
