% Code-Auto Generated By jmp8430 using gmt Toolbox on 05-Mar-2026 13:10:05
function res = sysFun_HeatExchanger(t,y,u1,u2,x4,x5)
x1 = y(1);
x2 = y(2);
x3 = y(3);
cpf_a = 1;
cpf_b = 1;
A_a = 1;
A_b = 1;
h_a = 1;
h_b = 1;
Rho_a = 1090;
Rho_b = 1090;
V_a = 0.001;
V_b = 0.001;
cp_w = 0.001;
m_w = 0.001;
x1_dot = (1/(cpf_a*V_a*Rho_a))*(+(cpf_a*u1*x4)-(cpf_a*u1*x1)+(h_a*A_a*(x3-x1)));
x2_dot = (1/(cpf_b*V_b*Rho_b))*(+(cpf_b*u2*x5)-(cpf_b*u2*x2)-(h_b*A_b*(x2-x3)));
x3_dot = (1/(cp_w*m_w))*(-(h_a*A_a*(x3-x1))+(h_b*A_b*(x2-x3)));
res = [x1_dot;x2_dot;x3_dot];
end
