% Code-Auto Generated By jmp8430 using gmt Toolbox on 13-Jan-2026 12:39:44
function res = sysFun_HeatExchanger(t,y,u1,u2)
cp_f1 = 1;
cp_f2 = 1;
HTC = 1;
x1 = y(1);
x2 = y(2);
x3 = y(3);
x4 = y(4);
x5 = y(5);
x6 = y(6);
x1_dot = (1/(1))*(+(cp_f1*u1*x3)-(cp_f1*u1*x1)-(HTC*(x1-x2)));
x2_dot = (1/(1))*(+(cp_f2*u2*x4)-(cp_f2*u2*x2)+(HTC*(x1-x2)));
x3_dot = (1/(1))*(-(cp_f1*u1*x3));
x4_dot = (1/(1))*(-(cp_f2*u2*x4));
x5_dot = (1/(1))*(+(cp_f1*u1*x1));
x6_dot = (1/(1))*(+(cp_f2*u2*x2));
res(1) = x1_dot;
res(2) = x2_dot;
res(3) = x3_dot;
res(4) = x4_dot;
res(5) = x5_dot;
res(6) = x6_dot;
res = res';
end
