% Code-Auto Generated By jmp8430 using gmt Toolbox on 13-Jan-2026 10:16:07
function res = sysFun_Engine(t,y,u1)
Qhv = 46000000;
J = 25;
Nth_c = 0.4;
Nth_a = 0.25;
xd = [1 112 223 334 445 556 667 778 889 1000];
yd = [0.0759666916908419 0.239916153553658 0.123318934835166 0.183907788282417 0.239952525664903 0.41726706908437 0.0496544303257421 0.902716109915281 0.944787189721646 0.49086409246808];
x1 = y(1);
x2 = y(2);
y1 = y(3);
y2 = y(4);
x1_dot = (1/(Qhv))*(-(Qhv*x2*u1));
x2_dot = (1/(J*x2))*(+(Qhv*x2*u1)-(interp1(xd,yd,x2)*Qhv*x2*u1)-(Nth_a*Qhv*x2*u1));
y1_ = (1/(1))*(+(interp1(xd,yd,x2)*Qhv*x2*u1))-y1;
y2_ = (1/(1))*(+(Nth_a*Qhv*x2*u1))-y2;
res(1) = x1_dot;
res(2) = x2_dot;
res(3) = y1_;
res(4) = y2_;
res = res';
end
