% Code-Auto Generated By jmp8430 using gmt Toolbox on 13-Jan-2026 13:03:40
function res = sysFun_DCMotor(t,y)
J = 1;
Cp = 1;
L = 1;
b = 1;
c = 1;
R = 1;
Kt = 1;
x1 = y(1);
x2 = y(2);
x3 = y(3);
x1_dot = (1/(L*x1))*(-(Kt*x1*x2)-(R*x1^2));
x2_dot = (1/(J*x2))*(+(Kt*x1*x2)-(b*x2^2+c*x2));
x3_dot = (1/(Cp))*(+(b*x2^2+c*x2)+(R*x1^2));
res(1) = x1_dot;
res(2) = x2_dot;
res(3) = x3_dot;
res = res';
end
