% Code-Auto Generated By jmp8430 using gmt Toolbox on 05-Mar-2026 12:01:18
% Inputs 
u1 = 1;% HeatExchanger: Mass Flow Rate - Fluid A
u2 = 1;% HeatExchanger: Mass Flow Rate - Fluid B
% Boundary Conditions
x4 = 200; % HeatExchanger: Source Temperature - Fluid A(External)
x5 = 150; % HeatExchanger: Source Temperature - Fluid B(External)
x6 = 300; % HeatExchanger: Sink Temperature - Fluid A(External)
x7 = 500; % HeatExchanger: Sink Temperature - Fluid B(External)
% Simulation Time
SimTEnd = 2000;
% Initial Conditions
x1_0 = 1;  %HeatExchanger: Temperature - Fluid A(Internal)
x2_0 = 1;  %HeatExchanger: Temperature - Fluid B(Internal)
x3_0 = 1;  %HeatExchanger: Wall Temperature(Internal)
y0 = [x1_0,x2_0,x3_0];
[t, y] = ode23s(@(t,y) sysFun_HeatExchanger(t,y,u1,u2,x4,x5,x6,x7), [0 SimTEnd], y0);
% Plot Only Internal State Types
InternalIdx = ([HeatExchanger.Vertices.VertexType] == gmt_VertexType.Internal);
yint = y(:,InternalIdx);
NumInternal = sum(InternalIdx);
DimSubPlot = max(ceil(sqrt(NumInternal)),2);
ylabels_tmp = [HeatExchanger.Vertices(InternalIdx).VertexName];
ylabelsnew_tmp = replace(ylabels_tmp, ":", newline);
figure
for i = 1:NumInternal
    subplot(DimSubPlot,DimSubPlot,i)
    plot(t,yint(:,i))
    xlabel('Time')
    ylabel(ylabelsnew_tmp(i))
end
