% Code-Auto Generated By jmp8430 using gmt Toolbox on 16-Mar-2026 10:06:09
function res = sysFun_MainTank(t,y,u1,u2,x4)
x1 = y(1);
x2 = y(2);
cp_f = 3300;
Rho = 1090;
V = 0.002;
x1_dot = (1/(cp_f*x2))*(+(cp_f*u1*x4)-(cp_f*u2*x1)-(cp_f*(u1-u2)*x1));
x2_dot = (1/(1))*(+((u1-u2)));
x3_ = (1/(1))*(-((u1-u2)));
x4_ = (1/(1))*(-(cp_f*u1*x4));
x5_ = (1/(1))*(+(cp_f*u2*x1));
x6_ = (1/(1))*(+(cp_f*(u1-u2)*x1));
res = [x1_dot;x2_dot];
end
