% Code-Auto Generated By jmp8430 using gmt Toolbox on 05-Mar-2026 12:04:13
% Inputs 
u1 = 1;% HeatLoad: Inlet Mass Flow 1
u2 = 2000;% HeatLoad: Energy Applied
% Boundary Conditions
x2 = 273; % HeatLoad: Sink Temperature(External)
x3 = 290; % HeatLoad: Source Temperature(External)
x4 = 1; % HeatLoad: Energy Applied(External)
% Simulation Time
SimTEnd = 2000;
% Initial Conditions
x1_0 = 1;  %HeatLoad: Load Temperature(Internal)
y0 = [x1_0];
[t, y] = ode23s(@(t,y) sysFun_HeatLoad(t,y,u1,u2,x2,x3,x4), [0 SimTEnd], y0);
% Plot Only Internal State Types
InternalIdx = ([HeatLoad.Vertices.VertexType] == gmt_VertexType.Internal);
yint = y(:,InternalIdx);
NumInternal = sum(InternalIdx);
DimSubPlot = max(ceil(sqrt(NumInternal)),2);
ylabels_tmp = [HeatLoad.Vertices(InternalIdx).VertexName];
ylabelsnew_tmp = replace(ylabels_tmp, ":", newline);
figure
for i = 1:NumInternal
    subplot(DimSubPlot,DimSubPlot,i)
    plot(t,yint(:,i))
    xlabel('Time')
    ylabel(ylabelsnew_tmp(i))
end
