% Code-Auto Generated By jmp8430 using gmt Toolbox on 05-Mar-2026 12:10:55
function res = sysFun_Split(t,y,u1,u2,u3,x2,x3,x4)
x1 = y(1);
cp_f = 3300;
V = 0.002;
Rho = 1090;
x1_dot = (1/(cp_f*V*Rho))*(+(u1*cp_f*x2)-(u2*cp_f*x1)-(u3*cp_f*x1));
res = [x1_dot];
end
