% Code-Auto Generated By jmp8430 using gmt Toolbox on 05-Mar-2026 13:09:39
% Boundary Conditions
x6 = 0; % Battery: Sink Temperature(External)
x7 = 0; % Battery: Current Load(External)
% Simulation Time
SimTEnd = 2000;
% Initial Conditions
x1_0 = 1;  %Battery: SOC(Internal)
x2_0 = 1;  %Battery: Voltage 1(Internal)
x3_0 = 1;  %Battery: Voltage 2(Internal)
x4_0 = 1;  %Battery: Cell Temperature(Internal)
x5_0 = 1;  %Battery: Surface Temperature(Internal)
y0 = [x1_0,x2_0,x3_0,x4_0,x5_0];
[t, y] = ode23s(@(t,y) sysFun_Battery(t,y,x6,x7), [0 SimTEnd], y0);
% Plot Only Internal State Types
InternalIdx = ([Battery.Vertices.VertexType] == gmt_VertexType.Internal);
yint = y(:,InternalIdx);
NumInternal = sum(InternalIdx);
DimSubPlot = max(ceil(sqrt(NumInternal)),2);
ylabels_tmp = [Battery.Vertices(InternalIdx).VertexName];
ylabelsnew_tmp = replace(ylabels_tmp, ":", newline);
figure
for i = 1:NumInternal
    subplot(DimSubPlot,DimSubPlot,i)
    plot(t,yint(:,i))
    xlabel('Time')
    ylabel(ylabelsnew_tmp(i))
end
