% Code-Auto Generated By jmp8430 using gmt Toolbox on 05-Mar-2026 11:46:42
function res = sysFun_Inverter(t,y,u1,x4,x5,x6)
x1 = y(1);
x2 = y(2);
x3 = y(3);
Ri = 0.0808;
Cp = 10000;
C = 0.1;
L = 0.01;
Ru = 0.0808;
x1_dot = (1/(C*x1))*(+(x2*x1)-(x1*x5));
x2_dot = (1/(L*x2))*(+(u1*sqrt(3/2)*x4*x2)-(x2*x1)-(u1*Ri*x2^2));
x3_dot = (1/(Cp))*(+(u1*Ri*x2^2)-((1/Ru)*(x3-x6)));
res = [x1_dot;x2_dot;x3_dot];
end
