% Code-Auto Generated By jmp8430 using gmt Toolbox on 05-Mar-2026 11:46:42
% Inputs 
u1 = 1;% Inverter: Inverter Duty Cycle
% Boundary Conditions
x4 = 12; % Inverter: Input Voltage(External)
x5 = 10; % Inverter: Current Load(External)
x6 = 273; % Inverter: Sink Temperature(External)
% Simulation Time
SimTEnd = 20;
% Initial Conditions
x1_0 = 13.88;  %Inverter: Voltage(Internal)
x2_0 = 10;  %Inverter: Current(Internal)
x3_0 = 250;  %Inverter: Temperature(Internal)
y0 = [x1_0,x2_0,x3_0];
[t, y] = ode23s(@(t,y) sysFun_Inverter(t,y,u1,x4,x5,x6), [0 SimTEnd], y0);
% Plot Only Internal State Types
InternalIdx = ([Inverter.Vertices.VertexType] == gmt_VertexType.Internal);
yint = y(:,InternalIdx);
NumInternal = sum(InternalIdx);
DimSubPlot = max(ceil(sqrt(NumInternal)),2);
ylabels_tmp = [Inverter.Vertices(InternalIdx).VertexName];
ylabelsnew_tmp = replace(ylabels_tmp, ":", newline);
figure
for i = 1:NumInternal
    subplot(DimSubPlot,DimSubPlot,i)
    plot(t,yint(:,i))
    xlabel('Time')
    ylabel(ylabelsnew_tmp(i))
end
