% Code-Auto Generated By jmp8430 using gmt Toolbox on 05-Mar-2026 12:04:13
function res = sysFun_HeatLoad(t,y,u1,u2,x2,x3,x4)
x1 = y(1);
cp_f = 3300;
V = 0.002;
Rho = 1090;
x1_dot = (1/(cp_f*V*Rho))*(+(cp_f*u1*x2)-(cp_f*u1*x1)+(u2));
res = [x1_dot];
end
