% Code-Auto Generated By jmp8430 using gmt Toolbox on 05-Mar-2026 13:35:52
function res = sysFun_Motor(t,y,x5)
x1 = y(1);
x2 = y(2);
x3 = y(3);
J = 0.000109;
Cp = 60;
L = 1.25219e-05;
b = 1.89435e-05;
c = 0.000234355;
Ra = 0.013462;
Kt = 0.00968816;
Ru = 0.00968816;
x1_dot = (1/(L*x1))*(-(Kt*x1*x2)-(Ra*x1^2)+(x1));
x2_dot = (1/(J*x2))*(+(Kt*x1*x2)-(b*x2^2+c*x2));
x3_dot = (1/(Cp))*(+(b*x2^2+c*x2)+(Ra*x1^2)-((x3-x5)/Ru));
x4_ = (1/(1))*(-(x1));
x5_ = (1/(1))*(+((x3-x5)/Ru));
res = [x1_dot;x2_dot;x3_dot];
end
