% Code-Auto Generated By jmp8430 using gmt Toolbox on 12-Feb-2026 09:41:28
function res = sysFun_MainTank(t,y,u1,u2)
cp_f = 3300;
Rho = 1090;
V = 0.002;
x1 = y(1);
x2 = y(2);
x3 = y(3);
x4 = y(4);
x5 = y(5);
x6 = y(6);
x1_dot = (1/(cp_f*x2))*(+(cp_f*u1*x4)-(cp_f*u2*x1)-(cp_f*(u1-u2)*x1));
x2_dot = (1/(1))*(+((u1-u2)));
x3_dot = 0;
x4_dot = 0;
x5_dot = (1/(cp_f*Rho*V))*(+(cp_f*u2*x1));
x6_dot = (1/(cp_f*Rho*V))*(+(cp_f*(u1-u2)*x1));
res = [x1_dot;x2_dot;x3_dot;x4_dot;x5_dot;x6_dot];
end
