% Code-Auto Generated By jmp8430 using gmt Toolbox on 11-Mar-2026 14:24:18
% Inputs 
u1 = 0; % Inverter: Inverter Duty Cycle (Units: unassigned)
% Boundary Conditions
x6 = 0; % Battery: Sink Temperature (Units: K)
x12 = 0; % DCMotor: Sink Temperature (Units: K)
x16 = 0; % Inverter: Sink Temperature (Units: K)
% Simulation Time
SimTEnd = 2000;
% Initial Conditions
x1_0 = 1;  % Battery: SOC (Units: %)
x2_0 = 1;  % Battery: Voltage 1 (Units: V)
x3_0 = 1;  % Battery: Voltage 2 (Units: V)
x4_0 = 1;  % Battery: Cell Temperature (Units: K)
x5_0 = 1;  % Battery: Surface Temperature (Units: K)
x8_0 = 1;  % DCMotor: Current (Units: A)
x9_0 = 1;  % DCMotor: Angular Velocity (Units: w)
x10_0 = 1;  % DCMotor: Temperature (Units: K)
x13_0 = 1;  % Inverter: Voltage (Units: V)
x14_0 = 1;  % Inverter: Current (Units: A)
x15_0 = 1;  % Inverter: Temperature (Units: K)
y0 = [x1_0,x2_0,x3_0,x4_0,x5_0,x8_0,x9_0,x10_0,x13_0,x14_0,x15_0];
[t, y] = ode23s(@(t,y) sysFun_BatteryElectric(t,y,u1,x6,x12,x16), [0 SimTEnd], y0);
% Plot Only Internal State Types
InternalIdx = ([BatteryElectric.Vertices.VertexType] == gmt_VertexType.Internal);
NumInternal = size(y,2);
DimSubPlot = max(ceil(sqrt(NumInternal)),2);
ylabels_tmp = [BatteryElectric.Vertices(InternalIdx).VertexName];
ylabelsnew_tmp = replace(ylabels_tmp, ":", newline);
figure
for i = 1:NumInternal
    subplot(DimSubPlot,DimSubPlot,i)
    plot(t,y(:,i))
    xlabel('Time')
    ylabel(ylabelsnew_tmp(i))
end
