% Code-Auto Generated By jmp8430 using gmt Toolbox on 05-Mar-2026 12:10:55
% Inputs 
u1 = 1;% Split: Inlet Mass Flow 1
u2 = 0.5;% Split: Outlet Mass Flow 1
u3 = 0.5;% Split: Outlet Mass Flow 2
% Boundary Conditions
x2 = 273; % Split: Sink_1(External)
x3 = 100; % Split: Source_2(External)
x4 = 300; % Split: Source_3(External)
% Simulation Time
SimTEnd = 2000;
% Initial Conditions
x1_0 = 1;  %Split: Junction Fluid Temperature(Internal)
y0 = [x1_0];
[t, y] = ode23s(@(t,y) sysFun_Split(t,y,u1,u2,u3,x2,x3,x4), [0 SimTEnd], y0);
% Plot Only Internal State Types
InternalIdx = ([Split.Vertices.VertexType] == gmt_VertexType.Internal);
yint = y(:,InternalIdx);
NumInternal = sum(InternalIdx);
DimSubPlot = max(ceil(sqrt(NumInternal)),2);
ylabels_tmp = [Split.Vertices(InternalIdx).VertexName];
ylabelsnew_tmp = replace(ylabels_tmp, ":", newline);
figure
for i = 1:NumInternal
    subplot(DimSubPlot,DimSubPlot,i)
    plot(t,yint(:,i))
    xlabel('Time')
    ylabel(ylabelsnew_tmp(i))
end
