% Code-Auto Generated By jmp8430 using gmt Toolbox on 11-Mar-2026 16:31:40
% Inputs 
u1 = 0; % Inverter: Inverter Duty Cycle (Units: unassigned)
% Boundary Conditions
x4 = 0; % DCMotor: Source Voltage (Units: V)
x5 = 0; % DCMotor: Sink Temperature (Units: K)
x9 = 0; % Inverter: Source Voltage (Units: V)
x10 = 0; % Inverter: Sink Temperature (Units: K)
% Simulation Time
SimTEnd = 2000;
% Initial Conditions
x1_0 = 1;  % DCMotor: Current (Units: A)
x2_0 = 1;  % DCMotor: Angular Velocity (Units: w)
x3_0 = 1;  % DCMotor: Temperature (Units: K)
x6_0 = 1;  % Inverter: Voltage (Units: V)
x7_0 = 1;  % Inverter: Current (Units: A)
x8_0 = 1;  % Inverter: Temperature (Units: K)
y0 = [x1_0,x2_0,x3_0,x6_0,x7_0,x8_0];
[t, y] = ode23s(@(t,y) sysFun_BatteryElectric(t,y,u1,x4,x5,x9,x10), [0 SimTEnd], y0);
% Plot Only Internal State Types
InternalIdx = ([BatteryElectric.Vertices.VertexType] == gmt_VertexType.Internal);
NumInternal = size(y,2);
DimSubPlot = max(ceil(sqrt(NumInternal)),2);
ylabels_tmp = [BatteryElectric.Vertices(InternalIdx).VertexName];
ylabelsnew_tmp = replace(ylabels_tmp, ":", newline);
figure
for i = 1:NumInternal
    subplot(DimSubPlot,DimSubPlot,i)
    plot(t,y(:,i))
    xlabel('Time')
    ylabel(ylabelsnew_tmp(i))
end
