% Code-Auto Generated By jmp8430 using gmt Toolbox on 05-Mar-2026 13:35:24
% Boundary Conditions
x4 = 0; % Motor: Source Voltage(External)
x5 = 0; % Motor: Sink Temperature(External)
% Simulation Time
SimTEnd = 2000;
% Initial Conditions
x1_0 = 1;  %Motor: Current(Internal)
x2_0 = 1;  %Motor: Angular Velocity(Internal)
x3_0 = 1;  %Motor: Temperature(Internal)
y0 = [x1_0,x2_0,x3_0];
[t, y] = ode23s(@(t,y) sysFun_Motor(t,y,x5), [0 SimTEnd], y0);
% Plot Only Internal State Types
InternalIdx = ([Motor.Vertices.VertexType] == gmt_VertexType.Internal);
yint = y(:,InternalIdx);
NumInternal = sum(InternalIdx);
DimSubPlot = max(ceil(sqrt(NumInternal)),2);
ylabels_tmp = [Motor.Vertices(InternalIdx).VertexName];
ylabelsnew_tmp = replace(ylabels_tmp, ":", newline);
figure
for i = 1:NumInternal
    subplot(DimSubPlot,DimSubPlot,i)
    plot(t,yint(:,i))
    xlabel('Time')
    ylabel(ylabelsnew_tmp(i))
end
