% Code-Auto Generated By jmp8430 using gmt Toolbox on 05-Mar-2026 12:07:00
% Inputs 
u1 = 1;% Tank: Inlet Mass Flow 1
u2 = 2;% Tank: Outlet Mass Flow 1
% Boundary Conditions
x3 = 1; % Tank: Mass Conservation(External)
x4 = 250; % Tank: Source Temperature(External)
x5 = 273; % Tank: Sink Temperature(External)
x6 = 200; % Tank: Internal Sink Temperature(External)
% Simulation Time
SimTEnd = 2000;
% Initial Conditions
x1_0 = 300;  %Tank: Temperature(Internal)
x2_0 = 6000;  %Tank: Mass(Internal)
y0 = [x1_0,x2_0];
[t, y] = ode23s(@(t,y) sysFun_Tank(t,y,u1,u2,x3,x4,x5,x6), [0 SimTEnd], y0);
% Plot Only Internal State Types
InternalIdx = ([Tank.Vertices.VertexType] == gmt_VertexType.Internal);
yint = y(:,InternalIdx);
NumInternal = sum(InternalIdx);
DimSubPlot = max(ceil(sqrt(NumInternal)),2);
ylabels_tmp = [Tank.Vertices(InternalIdx).VertexName];
ylabelsnew_tmp = replace(ylabels_tmp, ":", newline);
figure
for i = 1:NumInternal
    subplot(DimSubPlot,DimSubPlot,i)
    plot(t,yint(:,i))
    xlabel('Time')
    ylabel(ylabelsnew_tmp(i))
end
