% Code-Auto Generated By jmp8430 using gmt Toolbox on 13-Mar-2026 13:28:41
% Inputs 
u1 = 0; % MainTank: Inlet Mass Flow 1 (Units: kg/s)
u2 = 0; % MainTank: Outlet Mass Flow 1 (Units: kg/s)
% Boundary Conditions
x4 = 0; % MainTank: Source Temperature (Units: K)
% Simulation Time
SimTEnd = 2000;
% Initial Conditions
x1_0 = 1;  % MainTank: Temperature (Units: K)
x2_0 = 1;  % MainTank: Mass (Units: kg)
y0 = [x1_0,x2_0];
[t, y] = ode23s(@(t,y) sysFun_MainTank(t,y,u1,u2,x4), [0 SimTEnd], y0);
% Plot Only Internal State Types
InternalIdx = ([MainTank.Vertices.VertexType] == gmt_VertexType.Internal);
NumInternal = size(y,2);
DimSubPlot = max(ceil(sqrt(NumInternal)),2);
ylabels_tmp = [MainTank.Vertices(InternalIdx).VertexName];
ylabelsnew_tmp = replace(ylabels_tmp, ":", newline);
figure
for i = 1:NumInternal
    subplot(DimSubPlot,DimSubPlot,i)
    plot(t,y(:,i))
    xlabel('Time')
    ylabel(ylabelsnew_tmp(i))
end
