% Code-Auto Generated By jmp8430 using gmt Toolbox on 05-Mar-2026 15:06:36
function res = sysFun_MotorLin(t,y,x4,x5,A,B,Z)
x1 = y(1);
x2 = y(2);
x3 = y(3);

x_dot = A*y + Z; 
x1_dot = x_dot(1);
x2_dot = x_dot(2);
x3_dot = x_dot(3);

res = [x1_dot;x2_dot;x3_dot];
end
